### ISSUE TITLE
Update clean_text() function

### ISSUE THREAD

**Issue by akashmodak97** [jasmine1601/Sentiment-Analysis-of-Amazon-Reviews#1]
In addition to your clean_text() function, add these lines of code, because there are few symbols, that don't contribute to the sentiment of a sentence.

import re
REPLACE_BY_SPACE_RE = re.compile('[/(){}—\[\]\|@,;‘?|।!-॥–’-]')

def clean_text(text):
    """
        text: a string
        return: modified initial string
    """
    text = text.replace('\n',' ')
    #replace REPLACE_BY_SPACE_RE symbols by space in text
    text = REPLACE_BY_SPACE_RE.sub(' ', text) 
    return text

For more information, you can check [this](https://github.com/akashmodak97/Genre-detection-of-Bengali-Songs-Based-on-Lyrics/blob/master/Sentiment_Analysis_of_Rabindra_Sangeet_based_on_lyrics_to_detect_parjay(genre).ipynb) link. :)

**Comment by jasmine1601** [comment]
Ok I'll add :)
