### ISSUE TITLE
Issue template

### ISSUE THREAD

**Issue by jasmine1601** [jasmine1601/Sentiment-Analysis-of-Amazon-Reviews#5]
Create an issue template in the `/.github` directory, with filename `issue_template.md`. It should only contain the following details:

* File to be updated
* Changes that will be made
* How it will improve the project

**Comment by nidz27** [comment]
Can you please assign this issue to me? I would like to work on it. Also, please can you elaborate as to what all shoould the template include.

**Comment by jasmine1601** [comment]
@nidz27 the template should only include the 3 things mentioned above in bullets. Also, do join the Gitter channel.

**Comment by srini047** [comment]
@jasmine1601 Like to get assigned as per the gitter chat.

**Comment by jasmine1601** [comment]
@srini047 Assigned.
