### ISSUE TITLE
Pull request template

### ISSUE THREAD

**Issue by jasmine1601** [jasmine1601/Sentiment-Analysis-of-Amazon-Reviews#7]
Create a PR template in the `/.github` directory, with filename `pull_request_template.md`. It should only contain the following details:

* Related issue 
* File that has been updated
* Changes that have been made

**Comment by srini047** [comment]
Hi @jasmine1601, I will work on this issue too. I had one of my end-sem exams hence could work in a full-fledged manner. I am trying to resolve that issue and will work on this as well.

**Comment by jasmine1601** [comment]
@srini047 Sure, go for it.
